### PR TITLE
Retry in-case of EOF on parseResult

### PR DESCRIPTION
**Pull request by hectorj**
Related to #75 and https://github.com/aerospike/aerospike-server/issues/156

According to https://github.com/aerospike/aerospike-client-java/blob/master/client/src/com/aerospike/client/command/SyncCommand.java, all IO errors (even during parseResult) should lead to a retry.

Not very happy with the code duplication.
Improvements are welcome.
Sadly I don't have the time nor the right idea yet to refactor the error handling in this func.

### CODE REVIEW

**Comment by edbo** [comment]
Is there any timeline on this being brought into the main client? We relatively often get EOF errors coming in and sometimes it tends to hit in batches for some reason.

**Comment by hectorj** [comment]
@edbo : whether this or another similar PR gets merged, the best fix is to follow this recommendation: https://github.com/aerospike/aerospike-client-java/blob/66a0899462b89e85f8cca03e0ecd2d05d6035386/client/src/com/aerospike/client/policy/ClientPolicy.java#L65-L67

Set your client's [IdleTimeout](https://github.com/aerospike/aerospike-client-go/blob/9a5793109e5213056a459996ba0facf104186f71/client_policy.go#L39) lower than your server's `proto-fd-idle-ms`.

This PR will only make the client retry in case it does hit this error, but its better to not hit it at all.

**Comment by edbo** [comment]
We've done all of that already. For some reason it seems to happen to around 50% of requests all at once and across multiple application servers. Then it miraculously stops and goes back to normal.

**Comment by khaf** [comment]
Sorry for the delay in merging this PR and thanks for your patience. We'll get it into the client in the next release latest early next week.

**Comment by khaf** [comment]
Merged and in master.

**Pull request merged**
