### PR TITLE
misspelled and doc link fixes

### PR DESCRIPTION
**Pull request by pnutmath**
- misspell fixes
- pkg.go.dev links of documentation in README.md

### CODE REVIEW

**Comment by pnutmath** [comment]
@khaf

**Comment by khaf** [comment]
I'll pull this in for the next release. At this moment it's not clear to me when that is. Is there a reason you are in a rush for getting misspelling fixes in?

**Comment by pnutmath** [comment]
Nope, actually I wondering build failure!

**Comment by khaf** [comment]
I'm looking into it, hence why the next release date in unclear.

**Comment by pnutmath** [comment]
Fair enough!

**Pull request merged**
