### PR TITLE
Add missing AddObject method

### PR DESCRIPTION
**Pull request by on99**

### CODE REVIEW

**Comment by khaf** [comment]
Aside from the failed test, can you elaborate a bit on how this API is going to be used and why is it needed?

**Comment by on99** [comment]
```go
type statistics struct {
	ID          string `db:"id" as:"-"`
	Granularity string `db:"granularity" as:"-"`
	dimensions
	metrics
}

type dimensions struct {
	CreatedAt                    time.Time `db:"created_at" as:"-"`
	MonetizerID                  int64     `db:"monetizer_id" as:"d_mid,omitempty"`
	MonetizerAppID               int64     `db:"monetizer_app_id" as:"d_maid,omitempty"`
	MonetizerAppAdUnitID         int64     `db:"monetizer_app_ad_unit_id" as:"d_maauid,omitempty"`
	MonetizerSDKVersion          string    `db:"monetizer_sdk_version" as:"d_msv,omitempty"`
	MonetizerIntegrateType       string    `db:"monetizer_integrate_type" as:"d_mit,omitempty"`
	MonetizerAdType              int64     `db:"monetizer_ad_type" as:"d_mat,omitempty"`
	MonetizerDeviceOS            string    `db:"monetizer_device_os" as:"d_mdos,omitempty"`
	MonetizerCountry             string    `db:"monetizer_country" as:"d_mdcountry,omitempty"`
	MonetizerRegion              string    `db:"monetizer_region" as:"d_mdregion,omitempty"`
	MonetizerCity                string    `db:"monetizer_city" as:"d_mdcity,omitempty"`
	SchedulerID                  int64     `db:"scheduler_id" as:"d_sid,omitempty"`
	AdvertiserID                 int64     `db:"advertiser_id" as:"d_aid,omitempty"`
	AdvertiserAdType             int64     `db:"advertiser_ad_type" as:"d_aat,omitempty"`
	MonetizerAdSize              string    `db:"monetizer_ad_size" as:"d_mas,omitempty"`
	MonetizerAppVersion          string    `db:"monetizer_app_version" as:"d_mav,omitempty"`
	AdvertiserAdSize             string    `db:"advertiser_ad_size" as:"d_aas,omitempty"`
	RequestAdvertiserParameterID int64     `db:"request_advertiser_parameter_id" as:"d_rapid,omitempty"`
}

type metrics struct {
	RequestFromMonetizer                         int64   `db:"request_from_monetizer" as:"m_rfm,omitempty"`
	RequestFromMonetizerErrored                  int64   `db:"request_from_monetizer_errored" as:"m_rfme,omitempty"`
	RequestToAdvertiser                          int64   `db:"request_to_advertiser" as:"m_rta,omitempty"`
	RespondedFromAdvertiserErrored               int64   `db:"responded_from_advertiser_errored" as:"m_rfae,omitempty"`
	RespondedFromAdvertiserSuccessful            int64   `db:"responded_from_advertiser_successful" as:"m_rfas,omitempty"`
	RespondToMonetizerWithAd                     int64   `db:"respond_to_monetizer_with_ad" as:"m_rtmwa,omitempty"`
	RespondToMonetizerWithoutAd                  int64   `db:"respond_to_monetizer_without_ad" as:"m_rtmwouta,omitempty"`
	RespondToMonetizerTimeout                    int64   `db:"respond_to_monetizer_timeout" as:"m_rtmt,omitempty"`
	ImpressionAll                                int64   `db:"impression_all" as:"m_imp_all,omitempty"`
	ImpressionDuplicate                          int64   `db:"impression_duplicate" as:"m_imp_dup,omitempty"`
	ImpressionInvalidAdxPrice                    int64   `db:"impression_invalid_adx_price" as:"m_imp_iap,omitempty"`
	ImpressionTimeout                            int64   `db:"impression_timeout" as:"m_imp_to,omitempty"`
	Impression                                   int64   `db:"impression" as:"m_imp,omitempty"`
	ClickAll                                     int64   `db:"click_all" as:"m_click_all,omitempty"`
	ClickDuplicate                               int64   `db:"click_duplicate" as:"m_click_dup,omitempty"`
	ClickTimeout                                 int64   `db:"click_timeout" as:"m_click_to,omitempty"`
	Click                                        int64   `db:"click" as:"m_click,omitempty"`
	PlayStart                                    int64   `db:"play_start" as:"m_ps,omitempty"`
	PlayEnded                                    int64   `db:"play_ended" as:"m_pe,omitempty"`
	PlayBreak                                    int64   `db:"play_break" as:"m_pb,omitempty"`
	RespondedFromAdvertiserNoAd                  int64   `db:"responded_from_advertiser_without_ad" as:"m_rfana,omitempty"`
	EarnAmount                                   float64 `db:"earn_amount" as:"m_ea,omitempty"`
	MonetizerAmount                              float64 `db:"monetizer_amount" as:"m_ma,omitempty"`
	DownloadStart                                int64   `db:"download_start" as:"m_ds,omitempty"`
	DownloadEnded                                int64   `db:"download_ended" as:"m_de,omitempty"`
	AppInstalled                                 int64   `db:"app_installed" as:"m_ai,omitempty"`
	WinMonetizerAuction                          int64   `db:"win_monetizer_auction" as:"m_wma,omitempty"`
	DurationHandlingMonetizerRequest             int64   `db:"duration_handling_monetizer_request" as:"m_dhmr,omitempty"`
	DurationHandlingMonetizerRequestWithoutAd    int64   `db:"duration_handling_monetizer_request_without_ad" as:"m_dhmrwa,omitempty"`
	DurationHandlingMonetizerRequestErrored      int64   `db:"duration_handling_monetizer_request_errored" as:"m_dhmre,omitempty"`
	DurationRequestingAdvertiser                 int64   `db:"duration_requesting_advertiser" as:"m_dra,omitempty"`
	DurationRequestingAdvertiserWithoutAd        int64   `db:"duration_requesting_advertiser_without_ad" as:"m_drawa,omitempty"`
	DurationRequestingAdvertiserErrored          int64   `db:"duration_requesting_advertiser_errored" as:"m_drae,omitempty"`
	FailedValidationBeforeRequestAdvertiser      int64   `db:"failed_validation_before_request_advertiser" as:"m_fvbra,omitempty"`
	FailedValidationAfterRespondedFromAdvertiser int64   `db:"failed_validation_after_responded_from_advertiser" as:"m_fvarfa,omitempty"`
}
```

My scenario is to insert statistics data into aerospike, if exists, add metrics, so it's convenient to use `AddObject(policy, key, metrics)` instead of manually write all the metrics bin names.

**Comment by khaf** [comment]
As a policy, we don't accept special use cases in the code base. If a struct has other fields, this API would be useless, which I suspect it would be most of the time.
It would be easy to write a very simple marshal code for yourself to convert this struct into a `BinMap` so you can use the existing API.

**Comment by on99** [comment]
Yes, I am doing exactly the same thing as you said, by introducing an external library https://github.com/fatih/structs to marshal metrics into a `map[string]interface{}`, however, I still think it's more convenient if aerospike-client-go provides this method.

Please close the pull request if it violates your policy.

**Pull request closed without merging**
