### PR TITLE
Use Go Modules

### PR DESCRIPTION
**Pull request by reugn**

### CODE REVIEW

**Comment by ZzEeKkAa** [comment]
Any plans to merge it?

**Comment by khaf** [comment]
This will come with the up coming v5 release, planned to come out before the end of March.

**Comment by wzhusnap** [comment]
Currently we are using bazel. The change of go module may require an integration of bazel-gazelle, can we get a temporary build before release?

**Comment by khaf** [comment]
I'm pretty sure I got an email notification regarding module integration with Bazel. Was it deleted by the commenter?

**Comment by khaf** [comment]
Done in v5. Thanks.

**Pull request closed without merging**
