### PR TITLE
Added latency metrics for aerospike

### PR DESCRIPTION
**Pull request by shubham340**
Added latency metrics for aerospike. 
Metrics include ops/sec ,  >1ms, >8ms, >64ms for read and write operation for each namespace.

### CODE REVIEW

**Comment by khaf** [comment]
What is the rational for this to be inside the client code? There are other values like throughput that could also be added, but should they?

**Comment by shubham340** [comment]
Yes, they should be added. Ideally, we should have a single source for all fetching kinds of metrics. It should depend upon the end user/customer which metrics to track and which metrics to ignore.

**Comment by khaf** [comment]
The client code is already big and complicated enough. There's no reason one could not do this outside the client in a different codebase.

**Comment by shubham340** [comment]
We are already fetching latency metrics for our application. We thought these metrics can be helpful for the entire aerospike community who track these metrics.

**Comment by khaf** [comment]
Thank you for your contribution.

Let us discuss this internally and see if there is a consensus regarding bringing this second tier functionality inside the client code.

**Comment by khaf** [comment]
After internal talks, we came to the conclusion that we would like to have utility code outside the client.

Thanks for your contribution.

**Pull request closed without merging**
